include:
  - project: "platform/pipelines-templates"
    file: "/build/node/template-library-node-npm.yml"
    ref: "master"
  - project: "platform/pipelines-templates"
    file: "/build/node/template-library-node-npm-test-latest.yml"
    ref: "master"
